sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: cloud-sky-itcast
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 1
  wechat:
    appid: wx64f7d11f5a171630
    secret: 46db476bed718d6bcaf7ff2604f9aa31
